### DISCUSSION TITLE
Synology and Docker Compose

### DISCUSSION THREAD

**Discussion by robant85** [hargata/lubelog#323] [Q&A]
Maybe it's my ignorance with Docker compose, but every time I try to rebuild the project, the version doesn't upgrade. I've cleared my browser caches and even used a different PC. The version is stuck on the version that I built the container with. Does anyone have any pointers?

I'm also assuming that the version on the settings page is being updated properly.

**Comment by robant85** [comment]
Nevermind, I had to delete the image. Told ya .. ignorance.

**Reply by Judman** [reply]
Care to give a little more detail on why you have to delete the image? I am having issues upgrading.

**Reply by robant85** [reply]
I'm not exactly sure why I had to delete the image, but docker downloaded again on the next build. The image you have is outdated and should be upgraded anyway. I guess my docker was just having trouble updating the existing image. Deleting the image won't make you lose any data, so that was my next troubleshooting step

**Reply by Judman** [reply]
So I don't know what is going on. I have 1.3.8 pinned in the compose file. I delete all the images and docker compose pull again. Docker images shows v1.3.8, but when I check the version in the settings it still shows 1.3.6. This has me pulling my hair out.

**Reply by robant85** [reply]
Make sure you also clear your browser cache. That's documented in the upgrade steps. You can also check in a private browsing session. 

If the image is correct, then it's a browser issue.

**Reply by robant85** [reply]
![Screenshot_20241017-171604.png](https://github.com/user-attachments/assets/8c6ce00a-fe5d-42e9-80da-e2ec684a02aa)

For reference

**Reply by Judman** [reply]
Thanks for the reply, opening the site in incognito mode exhibits the same behavior.

![image](https://github.com/user-attachments/assets/685600d5-38f3-4f94-bb6c-759c68696750)

**Reply by robant85** [reply]
I'm out of guesses. Delete the image and container. Let it rebuild all. Also maybe just use the 'latest' tag? 

Wanna drop your compose here for review? Or maybe looks like you are using dockerfile with a run?

**Reply by Judman** [reply]
Yeah just following the standard compose in the repo. I typically `docker compose down`, remove the old image, change the image version, `docker compose pull`, ` docker compose up -d`.

I have been using `docker images` and `docker image rm <container ID>` to clean up the image while the container is down.

When remove the images and `docker compose up -d` it pulls new images and starts no problem, but checking in incognito, the version in settings is still old.

```
services:
  app:
    image: ghcr.io/hargata/lubelogger:v1.3.8
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - config:/App/config
      - data:/App/data
      - translations:/App/wwwroot/translations
      - documents:/App/wwwroot/documents
      - images:/App/wwwroot/images
      - temp:/App/wwwroot/temp
      - lubelog:/App/
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  config:
  data:
  translations:
  documents:
  images:
  temp:
  lubelog:
  keys:
```

**Reply by robant85** [reply]
Sorry, just getting back to this. Your yaml looks so much different than mine.

Are you still having issues? Are you using container manager or something like Portainer? 

There's a lot of blanks in there. Sharing my compose below. Note the "latest" on the image. Also, why are your volumes empty at the bottom? 

```
services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: LubeLogger
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    volumes:
      - /volume1/docker/lubelogger/config:/App/config
      - /volume1/docker/lubelogger/data:/App/data
      - /volume1/docker/lubelogger/documents:/App/wwwroot/documents
      - /volume1/docker/lubelogger/images:/App/wwwroot/images
      - /volume1/docker/lubelogger/log:/App/log
      - /volume1/docker/lubelogger/keys:/root/.aspnet/DataProtection-Keys
      - /volume1/docker/lubelogger/temp:/App/wwwroot/temp
    ports:
      - 8054:8080
    env_file:
      - stack.env
```
