### DISCUSSION TITLE
Cannot change locale in docker

### DISCUSSION THREAD

**Discussion by lockheed** [hargata/lubelog#566] [General]
Using docker. I tried changing locale as per https://docs.lubelogger.com/International%20Locale but it doesn't work. After restarting/re-loggin in, I still have only US units/dates.

Here's my docker-compose:

```
services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: lubelog
    build: .
    # volumes used to keep data persistent
    volumes:
      - /z/services/lubelog/conf:/App/config
      - /z/services/lubelog/data:/App/data
      - /z/services/lubelog/translations:/App/wwwroot/translations
      - /z/services/lubelog/documents:/App/wwwroot/documents
      - /z/services/lubelog/images:/App/wwwroot/images
      - /z/services/lubelog/temp:/App/wwwroot/temp
      - /z/services/lubelog/log:/App/log
      - /z/services/lubelog/keys:/root/.aspnet/DataProtection-Keys
    environment:
      - LC_ALL=en_PL
      - LANG=en_PL
      - TIMEZONE=Europe/Warsaw
```
