### DISCUSSION TITLE
Stuck on lubelogger

### DISCUSSION THREAD

**Discussion by Upstream2263** [hargata/lubelog#571] [Q&A] [answered]
I looked at the lubelogger docker container and it looks like something I can really use.  I'm new to the docker containers in general.  I've got several other containers that work great and I can spin this up fine.  For whatever reason, I can't seem to log in, even though I think I have everything right.

```
lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    restart: "unless-stopped"
    # volumes used to keep data persistent
    volumes:
      - /media/storage2/docker/lubelogger/config:/config
      - /media/storage2/docker/lubelogger/data:/data
      - /media/storage2/docker/lubelogger/translations:/translations
      - /media/storage2/docker/lubelogger/documents:/documents
      - /media/storage2/docker/lubelogger/images:/images
      - /media/storage2/docker/lubelogger/temp:/temp
      - /media/storage2/docker/lubelogger/log:/log
      - /media/storage2/docker/lubelogger/keys:/keys
    # expose port and/or use serving via traefik
    ports:
      - "8090:8090"
    env_file:
      - lubelogger.env 
```

I'm logging into the server like I do the other containers: 192.168.50.5:8090, but it just comes up "This site can't be reached, 192.168.50.5 refused to connect."

I'm running on Ubuntu 22.04 for both machines, ufw for the firewall.  I did allow port 8090, both on v4 and v6. Rebooting the machine hasn't done anything.  I'm not running traefik (although considering it for the future)
