### DISCUSSION TITLE
Important Upcoming 1.4.3 Changes

### DISCUSSION THREAD

**Discussion by hargata** [hargata/lubelog#787] [Announcements]
Note, this upcoming version has been evaluated as a small/no risk update for the majority of users, but if you have a nonstandard installation(NixOS, Proxmox, etc), this change can potentially break your installation.

**Description of Changes**

- In 1.4.3, user uploaded files (documents, images, translations, etc) will be moved out from the `wwwroot` folder, also known as the WebRootPath onto the `data` folder. The files will be automatically copied over like so:
  - `wwwroot/images` -> `data/images`  
  - `wwwroot/documents` -> `data/documents`
  - `wwwroot/translations` -> `data/translations`

- The userConfig.json file previously located in `config/userConfig.json` will also be moved to `data/config/userConfig.json`

**Who does this affect**

- If your installation requires the injection of the environment variable `DOTNET_CONTENTROOT` this is most likely going to break your installation especially if your contentroot folder differs from LubeLogger's working directory.

- If you have write-restrictions on the `data` folder.

If your installation of LubeLogger is relatively standard like the majority of users, meaning that, for Docker, you used the provided `docker-compose.yml`, or you use the Windows/Linux standalone executables and have been running the executable directly, this is unlikely to affect you.

**How to know if my installation is at risk**

Realistically, you can only test this on Docker unless you're willing to clone the repo and build LubeLogger yourself.

If you use Docker:

Create this docker-compose file:
```
---
version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:edge
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  data:
  keys:
```

1. Create a backup of your current LubeLogger instance
2. Spin up an instance of the `:edge` tagged docker image using the docker-compose example above.
3. Restore the backup on the `:edge` instance
4. Test and make sure everything works - try uploading attachments, thumbnails, etc.

**Reasoning**

- Because the WebRootPath is meant to be a read-only directory. 
  - Previously we have been writing files to the directory so that it can easily be served up to users, this in hindsight was a pretty bad idea.
- This allows us to be one step closer to simplifying the volume mounts for the docker container since the `data` volume is already mounted for the database.

**My installation is broken, what can I do to fix it?**

Depends on why it's broken, if it's because LubeLogger doesn't have write access to the `data` folder, the solution should be pretty straightforward. If it's due to an injected `DOTNET_CONTENTROOT` environment variable, the solution to that is to not use the injected environment variable and instead rely on setting the working directory for LubeLogger.
