### DISCUSSION TITLE
Change port for macvlan

### DISCUSSION THREAD

**Discussion by elgatho** [hargata/lubelog#967] [Q&A] [answered]
Hello,
I'm using macvlan for separating ip's is it possible to change port from 8080 to 80? 
with macvlan below ports will not work.
```
    ports:
      - 8080:8080

```
```
services:
  lubeloger:
    image: ghcr.io/hargata/lubelogger:latest
    volumes:
      - /docker-data/lubeloger/data:/App/data
      - /docker-data/lubeloger/keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik

    networks:
      servers_internal:
        ipv4_address: 192.168.20.32 
    restart: unless-stopped

networks:
  servers_internal:
    external: true


```
