### ISSUE TITLE
Simplify volume mounts

### ISSUE THREAD

**Issue by iloveicedgreentea** [hargata/lubelog#260]
To reduce operational burden and make it simpler to deploy, there should only be one volume needed like /app or something, and the application should then deal with having the right folders in place.

Love the tool thanks for making it

**Comment by hargata** [comment]
@MeurillonGuillaume the only thing stopping the app from being able to be fully deployed in a single volume is the data protection keys which has to live in `/root/.aspnet/DataProtection-Keys` instead of `/App` but you're right, all the other paths can technically be simplified to just `/App` and the app will create the folders automatically.

As for the docker compose...yeah, it's pretty outdated and I ought to update it someday, it was created a long time ago, but there are concerns about existing users missing their data if they are updating from multi volume to single volume since their data won't be in there.

I'm still going to leave this ticket open because it's not fully capable of running on a single volume due to the data protection keys volume.

**Comment by Judman** [comment]
> I've deployed the application using a single volume mounted to the `/App` path and it seems to work fine for me, but the `docker-compose.yml` could probably be updated, unless there is a specific reason to have it this way.

Care to share?

**Comment by hargata** [comment]
@Judman this should work.

```
---
version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - lubelog:/App/
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  lubelog:
  keys:

```

**Comment by MeurillonGuillaume** [comment]
@Judman @hargata that is indeed pretty similar to how I have it deployed, works just fine.

**Comment by redge76** [comment]
As pointed in the https://github.com/hargata/lubelog/issues/407 issue, this a pretty bad idea to make /app de volume.
I did not realize that /app contained code AND data.

**Comment by hargata** [comment]
@redge76 that makes sense, I'll re-open this story, but making this a single volume app is not going to be prioritized anytime soon.

**Comment by pecataToshev** [comment]
Adding my two cents:
I was not able to run the application with the given docker-compose file. I had to extract all the data directories separately, because it was not finding the startup file. This is the config that wored for me:
```yml
services:
  lubelogger:
    image: hargata/lubelogger:v1.4.0
    container_name: lubelogger
    hostname: lubelogger
    restart: unless-stopped
    
    volumes:
      - ./data/appConfig:/App/config
      - ./data/appData:/App/data
      - ./data/appImages:/App/wwwroot/images
      - ./data/protectionKeys:/root/.aspnet/DataProtection-Keys
    
    ports:
      - 8080:8080

    env_file:
      - .env
```
