### ISSUE TITLE
OIDC Implementation: Missing `state` Parameter

### ISSUE THREAD

**Issue by wkeiuluf** [hargata/lubelog#329]
I cannot use my OIDC provider ([Authelia](https://github.com/authelia/authelia/)) because LubeLogger is not including a `&state=something` parameter in the request URL.

Additional reading:
- https://auth0.com/docs/secure/attack-protection/state-parameters
- https://stackoverflow.com/questions/35165793/what-attack-does-the-state-parameter-in-openid-connect-server-flow-prevent
- https://github.com/authelia/authelia/issues/5566

**Comment by hargata** [comment]
I'll probably release a fix for this next week

**Comment by hargata** [comment]
This is scheduled to be released tomorrow(25/2).

**Comment by hargata** [comment]
Released in 1.2.3

LubeLogger will now generate a state token and pass it onto the IdP; however, I have set it to not validate the state echoed back by default since it will break IdP-initiated sessions. You can enable state validation by adding an environment variable, see [OpenID Authentication in LubeLogger](https://docs.lubelogger.com/OpenID)

**Comment by hargata** [comment]
@wkeiuluf do you have any console errors?

**Comment by hargata** [comment]
we don't log the JWT / JSON response from the OpenID Provider for security reasons. I don't have any experience with Authelia so I can't really troubleshoot this.

- Does LL make a POST request to the Token URL of your Authelia instance? I'm not sure if Authelia logs this, but that will be a good place to start.

**Comment by shall0pass** [comment]
I also have not gotten Authelia to work with LubeLogger.  When I select the Login with Authelia button, I'm taken to authelia and given the option to authorize lubelogger.  I'm then redirected to the login page, but nothing further happens.  I use the same endpoints with Audio book shelf with no issues.

My authelia client section:
```
    - client_id: lube
      client_name: LubeLogger
      client_secret: 'secret'
      public: false
      authorization_policy: two_factor
      pre_configured_consent_duration: 1M
      scopes:
        - openid
        - email
        - profile
      grant_types:
        - 'authorization_code'
      redirect_uris:
        - https://lube.xxxxxx.cc/Login/RemoteAuth
      userinfo_signed_response_alg: none
      token_endpoint_auth_method: 'client_secret_post'
```
My lubelogger compose.yml:
```
version: "3.4"
services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - config:/App/config
      - data:/App/data
      - translations:/App/wwwroot/translations
      - documents:/App/wwwroot/documents
      - images:/App/wwwroot/images
      - temp:/App/wwwroot/temp
      - log:/App/log
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 5230:8080
    environment:
      - OpenIDConfig__Name=Authelia
      - OpenIDConfig__ClientId=lube
      - OpenIDConfig__ClientSecret=secret
      - OpenIDConfig__AuthURL=https://auth.xxxxx.cc/api/oidc/authorization
      - OpenIDConfig__TokenURL=https://auth.xxxxx.cc/api/oidc/token
      - OpenIDConfig__RedirectURL=https://lube.xxxxx.cc/Login/RemoteAuth
      - OpenIDConfig__Scope=email
      - OpenIDConfig__ValidateState=true
      - OpenIDConfig__DisableRegularLogin=false
      - OpenIDConfig__LogOutURL=https://auth.xxxxx.cc/api/oidc/logout
    env_file:
      - .env
    networks:
      - network1
networks:
  network1:
    name: proxynet
    external: true
volumes:
  config: null
  data: null
  translations: null
  documents: null
  images: null
  temp: null
  log: null
  keys: null
```
