### ISSUE TITLE
[Bug] Environment variables not read

### ISSUE THREAD

**Issue by thmsdelange** [hargata/lubelog#456]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
Whatever I try, I cannot get the lubelogger instance to read the environment variables I set. I can confirm that the environment variables are read within the docker-compose.yml by specifying env vars for e.g. the port that the program should run on. However, setting the language and OIDC variables doesn't have any effect on the container.

docker-compose.yml 
```
version: "3.4"

services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.2.9
    container_name: lubelogger
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - $APPDATA/lubelogger/config:/App/config
      - $APPDATA/lubelogger/data:/App/data
      - $APPDATA/lubelogger/translations:/App/wwwroot/translations
      - $APPDATA/lubelogger/documents:/App/wwwroot/documents
      - $APPDATA/lubelogger/images:/App/wwwroot/images
      - $APPDATA/lubelogger/temp:/App/wwwroot/temp
      - $APPDATA/lubelogger/log:/App/log
      - $APPDATA/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "127.0.0.1:$LUBE_PORT:8080"
    env_file:
      - .env
```

I have also tried to set the environment variables directly inside the docker-compose.yml by adding these lines:
```
    environment:
      - LC_ALL=en_GB
      - LANG=en_GB
```
this also does not have an effect on the lubelogger instance. After every change I made I recreate the container
```
sudo docker compose up -d --force-recreate
```
I also have tried purging and rebuilding the image serveral times
```
sudo docker build -t lubelogger -f Dockerfile .
```
but this also does not have any effect.

Platform is docker running on debian 12.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
No console errors

**App/Container Console Error**
No console errors

**Screenshots(optional)**
Not applicable

**Comment by hargata** [comment]
are you building the image yourself or using the pre-compiled docker image from GitHub?

**Comment by chris1284** [comment]
pre defined image works with environment ( i have directly set the environment variables in environment section, not in extra file, but it should be the same) . latest Version

**Comment by thmsdelange** [comment]
> are you building the image yourself or using the pre-compiled docker image from GitHub?
> 
> If you're building the image yourself then it doesn't make sense that the image in the docker-compose is still pointed at the GHCR image.


I guess both? The documentation is not really clear on that matter. It says to clone the repo, build the image and then use the docker-compose.yml in which the GHCR is linked.

**Comment by hargata** [comment]
when you run `docker inspect <container id>` does it show the environment variables being passed in?

**Comment by chris1284** [comment]
today i tried to setup smtp an do not get errors in log, but on app and mails are not send. i started a console into container and got 
```
$ docker exec -it lubelogger bash
bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF8)
if i look into the container
```
are there locales missing?
```
# locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
```

**Comment by hargata** [comment]
@chris1284 try just de_DE or de_DE.UTF-8

seems like you're missing a dash.

**Comment by chris1284** [comment]
> @chris1284 try just de_DE or de_DE.UTF-8
> 
> seems like you're missing a dash.

this was from testing, wrong copy. it is the same with de_DE or de_DE.UTF-8. if i install locales and reconfigure to "de_DE-UTF-8 UTF8" , de_DE.UTF-8 is working and no errors

**Comment by chris1284** [comment]
@hargata sadly not.

**Comment by chris1284** [comment]
@chris1284  yes, in docker-compose.yml with quotes and inside the container env shows the pw without quotes (like in the link). the password has spaces in (google does this). could be this is the problem

**Comment by hargata** [comment]
@chris1284 try port 587 for MailConfig__Port

**Comment by hargata** [comment]
@chris1284 well according to Microsoft, what Microsoft calls SSL is referred by Gmail as TLS, since LubeLogger is a .NET app, it also calls it SSL like Microsoft does.

https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?view=net-8.0

Gmail's TLS port is 587, the SSL-only port 465 is not supported.

**Comment by thmsdelange** [comment]
Couldn't find the time last week to come back at this. I debugged a little and still no luck. The environment variables are correctly passed to the container, they are visible with `docker inspect lubelogger`. The settings of the environment variables are however not passed to lubelogger itself it seems. When I go to my lubelogger instance it does not have oauth authentication nor does it have another locale.

docker-compose.yml:
```
version: "3.4"

services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.3.0
    container_name: lubelogger
    build: .
    restart: unless-stopped
    volumes:
      - $APPDATA/lubelogger/config:/App/config
      - $APPDATA/lubelogger/data:/App/data
      - $APPDATA/lubelogger/translations:/App/wwwroot/translations
      - $APPDATA/lubelogger/documents:/App/wwwroot/documents
      - $APPDATA/lubelogger/images:/App/wwwroot/images
      - $APPDATA/lubelogger/temp:/App/wwwroot/temp
      - $APPDATA/lubelogger/log:/App/log
      - $APPDATA/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "127.0.0.1:$LUBE_PORT:8080"
    env_file:
      - .env
```

.env:
```
LC_ALL=nl_NL.UTF-8
LANG=nl_NL.UTF-8
#MailConfig__EmailServer=""
#MailConfig__EmailFrom=""
#MailConfig__UseSSL="false"
#MailConfig__Port=587
#MailConfig__Username=""
#MailConfig__Password=""
LOGGING__LOGLEVEL__DEFAULT=Debug

OpenIDConfig__Name=LubeLogger
OpenIDConfig__ClientId=***
OpenIDConfig__ClientSecret=***
OpenIDConfig__AuthURL=https://domain.tld/application/o/authorize/
OpenIDConfig__TokenURL=https://domain.tld/application/o/token/
OpenIDConfig__RedirectURL=https://domain.tld/Login/RemoteAuth
OpenIDConfig__Scope='email'
OpenIDConfig__ValidateState=true
OpenIDConfig__DisableRegularLogin=true
OpenIDConfig__LogOutURL=https://domain.tld/application/o/lubelogger/end-session/

# * Uncoment this line if you use postgresSQL as database backend.
# * Check the docker-compose.postgresql.yml file
#POSTGRES_CONNECTION="Host=postgres;Username=lubelogger;Password=lubepass;Database=lubelogger;"

APPDATA=/path/to/appdata
LUBE_PORT=PORT
```
