### ISSUE TITLE
Why use "build ." in the docker compose file?

### ISSUE THREAD

**Issue by abosaad11** [hargata/lubelog#892]
I use Portainer, so today when I tried to update Lublogger I had this error:

```
Deployment error
Failed to deploy a stack: compose build operation failed: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

It didn't work until I commented out the "build ." line:

```
services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
#    build: .
```
Then it worked.

What's the purpose of that line when we already have a built image? Can I continue using the software without it?

Thank you
